### ISSUE TITLE
toolchanger not finding kuka_kvp_hw_interface

### ISSUE THREAD

**Issue by mahaarbo** [itk-thrivaldi/thrivaldi_moveit_examples#1]
Seems like the library for `kuka_kvp_hw_interface` is not available to the `toolchanger` for some reason.
Error message:
```
CMake Error at /home/mathia/Programming/arbo_ws/devel/share/kuka_kvp_hw_interface/cmake/kuka_kvp_hw_interfaceConfig.cmake:148 (message):
  Project 'toolchanger' tried to find library 'kuka_kvp_hw_interface'.  The
  library is neither a target nor built/installed properly.  Did you compile
  project 'kuka_kvp_hw_interface'? Did you find_package() it before the
  subdirectory containing its code is included?
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  thrivaldi_examples/toolchanger/CMakeLists.txt:10 (find_package)
```

Maybe an error in how `toolchanger` depends on `kuka_kvp_hw_interface`?

**Comment by ivareri** [comment]
Was due to an error from `kuka_kvp_hw_interface`. A nonexisting library in catkin_depend caused the library export to fail silently. Fixed in https://github.com/itk-thrivaldi/kuka_kvp_hw_interface/commit/84ef6eb39b89840a620de52105069e92fec102b6
