### ISSUE TITLE
Rename to thrivaldi_moveit_examples?

### ISSUE THREAD

**Issue by mahaarbo** [itk-thrivaldi/thrivaldi_moveit_examples#2]
If we agree on renaming this to thrivaldi_moveit_examples, I'll just go ahead and change it. Giving a heads up in case @ivareri needs to push any local changes.

**Comment by ivareri** [comment]
No unpushed changes, but maybe add a note in the new repo about the rename, as it was referenced by the old name in the thesis

**Comment by mahaarbo** [comment]
Done, see: https://github.com/itk-thrivaldi/thrivaldi_moveit_examples/commit/4f712db97730c83d92aa00dcc8046abee6b994f4 and https://github.com/itk-thrivaldi/thrivaldi_examples/commit/45f74cb3f93552f17744ed8c88f4eb1b34c74583
